apiVersion: v1 
kind: Service 
metadata:  
  name: hasher 
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 38080
  selector:    
      app: hasher
