apiVersion: v1 
kind: Service 
metadata:  
  name: redis 
spec:  
  type: NodePort
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
      nodePort: 6379
  selector:    
      app: redis
